version: '3'
services:
  api:
    container_name: api_nestjs_primeiros_passos
    build: ./nestjs/api-nestjs-primeiros-passos
    ports:
      - 3000:3000
    environment:
      INSTANCE_HOST: "postgres"
      DB_PORT: 5432
      DB_PASS: pgpass
      DB_USER: postgres
      DB_NAME: "nestjs_primeiros_passos"
      SWAGGER_USER: admin
      SWAGGER_PASSWORD: swagger
      NODE_ENV: dev
    volumes:
      - ./nestjs/api-nestjs-primeiros-passos:/home/node/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: "nestjs_primeiros_passos"
    volumes:
      - ./db/postgres/pgdata:/var/lib/postgresql/data
